name: BestDummy
version: 1.0
main: com.plugins.bestdummy.BestDummy
api-version: 1.12
commands:
  bestdummy:
    description: 生成或管理假人
    usage: |
      /bestdummy create <假人英文id> - 生成一个假人
      /bestdummy remove <假人英文id> - 删除一个假人
      /bestdummy removeall - 删除所有假人
    permission: bestdummy.use
permissions:
  bestdummy.use:
    description: 允许玩家使用 /bestdummy 指令
    default: true
